name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      # Client

      - name: Install Client Dependencies
        working-directory: client
        run: npm install

      - name: Build Client
        working-directory: client
        run: npm run build

      # Server

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run Server Tests
        working-directory: server
        run: npm test --if-present
